### ISSUE TITLE
build-emacs-from-tar fails with 24.1 and macOS 15.1.1 and Command Line Tools (no Xcode)

### ISSUE THREAD

**Issue by e40** [caldwell/build-emacs#142]
```
$ build-emacs-from-tar emacs-29.4.tar.bz2 release
==> Building pkg-config-0.29
==> Unpacking pkg-config-0.29
==> Configuring pkg-config-0.29
==> Making pkg-config-0.29
/Users/layer/src/import/build-emacs/build.rb:112:in `rescue in make': Make failed in build/pkg-config-0.29 (RuntimeError)
	from /Users/layer/src/import/build-emacs/build.rb:109:in `make'
	from /Users/layer/src/import/build-emacs/build.rb:87:in `build'
	from /Users/layer/src/import/build-emacs/build-dependencies.rb:65:in `block in ensure'
	from /Users/layer/src/import/build-emacs/build-dependencies.rb:63:in `each'
	from /Users/layer/src/import/build-emacs/build-dependencies.rb:63:in `ensure'
	from ./build-emacs-from-tar:149:in `prepare_extra_deps'
	from ./build-emacs-from-tar:236:in `<main>'
/Users/layer/src/import/build-emacs/verbose-shell.rb:40:in `system': 

440 |   return g_atomic_pointer_or ((volatile gpointer *) atomic, val);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gatomic.h:184:44: note: expanded from macro 'g_atomic_pointer_or'
  184 |     (gsize) __sync_fetch_and_or ((atomic), (val));                           \
      |                                            ^~~~~
gatomic.c:464:10: error: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]
  464 |   return g_atomic_pointer_xor ((volatile gpointer *) atomic, val);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gatomic.h:191:45: note: expanded from macro 'g_atomic_pointer_xor'
  191 |     (gsize) __sync_fetch_and_xor ((atomic), (val));                          \
      |                                             ^~~~~
4 errors generated.
make[6]: *** [libglib_2_0_la-gatomic.lo] Error 1
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [all-recursive] Error 1
make[4]: *** [all] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
💩  Command "make" returned 2
	from /Users/layer/src/import/build-emacs/build.rb:110:in `make'
	from /Users/layer/src/import/build-emacs/build.rb:87:in `build'
	from /Users/layer/src/import/build-emacs/build-dependencies.rb:65:in `block in ensure'
	from /Users/layer/src/import/build-emacs/build-dependencies.rb:63:in `each'
	from /Users/layer/src/import/build-emacs/build-dependencies.rb:63:in `ensure'
	from ./build-emacs-from-tar:149:in `prepare_extra_deps'
	from ./build-emacs-from-tar:236:in `<main>'
```

**Comment by e40** [comment]
```
$ xcode-select -v
xcode-select version 2409.
$ 
```

**Comment by thynus** [comment]
See:
https://github.com/caldwell/build-emacs/issues/145

I had very similar errors on build.

**Comment by caldwell** [comment]
Building the dependencies using the built-in dependency builder isn't really supported any more and so I can't guarantee that what's there will still work. You'll see a `patches` directory with some fixes for compilation issues I ran into last time I used it. 

That's why I eventually moved away from using that method--this kind of finicky "upgrade the compiler and things break" was too annoying to keep on top of. Having to track down random compiler errors in dependencies of dependencies got really old after a while 🙂.

Currently all my builds use [Nix](https://nixos.org/download/#nix-install-macos) to automatically get dependencies, but it should work with manual dependency management using Homebrew/MacPorts/whatever as long as those dependencies are in your path when you run `build-emacs-from-tar --no-deps` (`--no-deps` should really be called `--no-automatic-deps` or something). Check the output of `configure` to see if it is detecting your dependencies.
